name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2
#       - name: Build the Docker image
#         run: docker build . --file Dockerfile --tag kms-server:$(date +%s)
#       - name: Push to GitHub Packages
#         uses: docker/build-push-action@v2



jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: chinafengzhao/openjdk-alpine-with-chinese-timezone
          tag_with_ref: true
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: fengzhao/openjdk-alpine-with-chinese-timezone/openjdk
          tag_with_ref: true
